//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RTParams {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RTParams() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSTool.Properties.RTParams", typeof(RTParams).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Bot.
        /// </summary>
        public static string RT_PARAMS_FUKASHI_BOT {
            get {
                return ResourceManager.GetString("RT_PARAMS_FUKASHI_BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Left.
        /// </summary>
        public static string RT_PARAMS_FUKASHI_LEFT {
            get {
                return ResourceManager.GetString("RT_PARAMS_FUKASHI_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Right.
        /// </summary>
        public static string RT_PARAMS_FUKASHI_RIGHT {
            get {
                return ResourceManager.GetString("RT_PARAMS_FUKASHI_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Top.
        /// </summary>
        public static string RT_PARAMS_FUKASHI_TOP {
            get {
                return ResourceManager.GetString("RT_PARAMS_FUKASHI_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBAR_TYPE.
        /// </summary>
        public static string RT_PARAMS_REBAR_TYPE {
            get {
                return ResourceManager.GetString("RT_PARAMS_REBAR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 符号.
        /// </summary>
        public static string RT_PARAMS_STRUCTURE_NAME {
            get {
                return ResourceManager.GetString("RT_PARAMS_STRUCTURE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 符号.
        /// </summary>
        public static string RT_PARAMS_SYMBOL_NAME {
            get {
                return ResourceManager.GetString("RT_PARAMS_SYMBOL_NAME", resourceCulture);
            }
        }
    }
}


