//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSTool.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallRebarBeamV2Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallRebarBeamV2Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSTool.Properties.Langs.InstallRebarBeamV2Langs", typeof(InstallRebarBeamV2Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallRebarBeamView.
        /// </summary>
        public static string IRBV2_COMMAND_NAME {
            get {
                return ResourceManager.GetString("IRBV2_COMMAND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Bot.
        /// </summary>
        public static string IRBV2_FUKASHI_BOT {
            get {
                return ResourceManager.GetString("IRBV2_FUKASHI_BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Left.
        /// </summary>
        public static string IRBV2_FUKASHI_LEFT {
            get {
                return ResourceManager.GetString("IRBV2_FUKASHI_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Right.
        /// </summary>
        public static string IRBV2_FUKASHI_RIGHT {
            get {
                return ResourceManager.GetString("IRBV2_FUKASHI_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Fukashi.
        /// </summary>
        public static string IRBV2_FUKASHI_TITLE {
            get {
                return ResourceManager.GetString("IRBV2_FUKASHI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fukashi Top.
        /// </summary>
        public static string IRBV2_FUKASHI_TOP {
            get {
                return ResourceManager.GetString("IRBV2_FUKASHI_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string IRBV2_GROUP_NAME {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Anchor.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_ANCHOR {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_ANCHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Beam.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_BEAM {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_BEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Dantory.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_DANTORY {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_DANTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Rebar Bot.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_REBAR_BOT {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_REBAR_BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SideBar.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_REBAR_SIDE {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_REBAR_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Stirrup.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_REBAR_STIRRUP {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_REBAR_STIRRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Rebar Top.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_REBAR_TOP {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_REBAR_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section End.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_SECTION_END {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_SECTION_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Mid.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_SECTION_MID {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_SECTION_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Start.
        /// </summary>
        public static string IRBV2_GROUP_SETTING_SECTION_START {
            get {
                return ResourceManager.GetString("IRBV2_GROUP_SETTING_SECTION_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Cover.
        /// </summary>
        public static string IRBV2_SETTING_COVER {
            get {
                return ResourceManager.GetString("IRBV2_SETTING_COVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTANCE_R_TO_R.
        /// </summary>
        public static string IRBV2_SETTING_DISTANCE_R_TO_R {
            get {
                return ResourceManager.GetString("IRBV2_SETTING_DISTANCE_R_TO_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string IRBV2_SETTING_REBAR_DIAMETER {
            get {
                return ResourceManager.GetString("IRBV2_SETTING_REBAR_DIAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string IRBV2_SETTING_REBAR_QUANTITY {
            get {
                return ResourceManager.GetString("IRBV2_SETTING_REBAR_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        public static string IRBV2_SETTING_REBAR_SPACING {
            get {
                return ResourceManager.GetString("IRBV2_SETTING_REBAR_SPACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Span.
        /// </summary>
        public static string IRBV2_SETTING_SPAN {
            get {
                return ResourceManager.GetString("IRBV2_SETTING_SPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Beam.
        /// </summary>
        public static string IRBV2_TAB_SETTING_BEAM {
            get {
                return ResourceManager.GetString("IRBV2_TAB_SETTING_BEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Section.
        /// </summary>
        public static string IRBV2_TAB_SETTING_SECTION {
            get {
                return ResourceManager.GetString("IRBV2_TAB_SETTING_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirrup Type.
        /// </summary>
        public static string IRBV2_TAB_SETTING_STIRRUP_TYPE {
            get {
                return ResourceManager.GetString("IRBV2_TAB_SETTING_STIRRUP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Setting.
        /// </summary>
        public static string IRBV2_TAB_SETTING_SUB_SETTING {
            get {
                return ResourceManager.GetString("IRBV2_TAB_SETTING_SUB_SETTING", resourceCulture);
            }
        }
    }
}


