//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSTool.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RebarScheduleParameter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RebarScheduleParameter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSTool.Properties.Langs.RebarScheduleParameter", typeof(RebarScheduleParameter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAP_COUPLER_END.
        /// </summary>
        public static string LAP_COUPLER_END {
            get {
                return ResourceManager.GetString("LAP_COUPLER_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAP_COUPLER_START.
        /// </summary>
        public static string LAP_COUPLER_START {
            get {
                return ResourceManager.GetString("LAP_COUPLER_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAP_PLATE_END.
        /// </summary>
        public static string LAP_PLATE_END {
            get {
                return ResourceManager.GetString("LAP_PLATE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAP_PLATE_START.
        /// </summary>
        public static string LAP_PLATE_START {
            get {
                return ResourceManager.GetString("LAP_PLATE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAP_WELD_END.
        /// </summary>
        public static string LAP_WELD_END {
            get {
                return ResourceManager.GetString("LAP_WELD_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAP_WELD_START.
        /// </summary>
        public static string LAP_WELD_START {
            get {
                return ResourceManager.GetString("LAP_WELD_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBAR_TYPE.
        /// </summary>
        public static string REBAR_TYPE {
            get {
                return ResourceManager.GetString("REBAR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_COUPLER_QUANTITY.
        /// </summary>
        public static string SCHEDULE_REBAR_COUPLER_QUANTITY {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_COUPLER_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_DIAMETER_NAME.
        /// </summary>
        public static string SCHEDULE_REBAR_DIAMETER_NAME {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_DIAMETER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_GEOMETRY_SHAPE.
        /// </summary>
        public static string SCHEDULE_REBAR_GEOMETRI_SHAPE {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_GEOMETRI_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_GROUP_LEVEL.
        /// </summary>
        public static string SCHEDULE_REBAR_GROUP_LEVEL {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_GROUP_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_HOST_NAME.
        /// </summary>
        public static string SCHEDULE_REBAR_HOST_NAME {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_HOST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_HOST_POSITION.
        /// </summary>
        public static string SCHEDULE_REBAR_HOST_POSITION {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_HOST_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_HOST_QUANTITY.
        /// </summary>
        public static string SCHEDULE_REBAR_HOST_QUANTITY {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_HOST_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_IMAGE_ORDER.
        /// </summary>
        public static string SCHEDULE_REBAR_IMAGE_ORDER {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_IMAGE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_LENGTH.
        /// </summary>
        public static string SCHEDULE_REBAR_LENGTH {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_LENGTH_COUNT_CUT.
        /// </summary>
        public static string SCHEDULE_REBAR_LENGTH_COUNT_CUT {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_LENGTH_COUNT_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_LENGTH_ORDER.
        /// </summary>
        public static string SCHEDULE_REBAR_LENGTH_ORDER {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_LENGTH_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_LEVEL.
        /// </summary>
        public static string SCHEDULE_REBAR_LEVEL {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_MARK.
        /// </summary>
        public static string SCHEDULE_REBAR_MARK {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_MATERIAL.
        /// </summary>
        public static string SCHEDULE_REBAR_MATERIAL {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_PLATE_LAP_QUANTITY.
        /// </summary>
        public static string SCHEDULE_REBAR_PLATE_LAP_QUANTITY {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_PLATE_LAP_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_QUANTITY.
        /// </summary>
        public static string SCHEDULE_REBAR_QUANTITY {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_SHAPE.
        /// </summary>
        public static string SCHEDULE_REBAR_SHAPE {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_TOTAL_QUANTITY.
        /// </summary>
        public static string SCHEDULE_REBAR_TOTAL_QUANTITY {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_TOTAL_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_TOTAL_QUANTITY_AFTER_CUT.
        /// </summary>
        public static string SCHEDULE_REBAR_TOTAL_QUANTITY_AFTER_CUT {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_TOTAL_QUANTITY_AFTER_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_WELD_QUANTITY.
        /// </summary>
        public static string SCHEDULE_REBAR_WELD_QUANTITY {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_WELD_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_ZONE.
        /// </summary>
        public static string SCHEDULE_REBAR_ZONE {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE_REBAR_ZONE_SELECTED.
        /// </summary>
        public static string SCHEDULE_REBAR_ZONE_SELECTED {
            get {
                return ResourceManager.GetString("SCHEDULE_REBAR_ZONE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_A.
        /// </summary>
        public static string SEGMENT_A {
            get {
                return ResourceManager.GetString("SEGMENT_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_B.
        /// </summary>
        public static string SEGMENT_B {
            get {
                return ResourceManager.GetString("SEGMENT_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_C.
        /// </summary>
        public static string SEGMENT_C {
            get {
                return ResourceManager.GetString("SEGMENT_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_D.
        /// </summary>
        public static string SEGMENT_D {
            get {
                return ResourceManager.GetString("SEGMENT_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_E.
        /// </summary>
        public static string SEGMENT_E {
            get {
                return ResourceManager.GetString("SEGMENT_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_F.
        /// </summary>
        public static string SEGMENT_F {
            get {
                return ResourceManager.GetString("SEGMENT_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_G.
        /// </summary>
        public static string SEGMENT_G {
            get {
                return ResourceManager.GetString("SEGMENT_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_H.
        /// </summary>
        public static string SEGMENT_H {
            get {
                return ResourceManager.GetString("SEGMENT_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_J.
        /// </summary>
        public static string SEGMENT_J {
            get {
                return ResourceManager.GetString("SEGMENT_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_K.
        /// </summary>
        public static string SEGMENT_K {
            get {
                return ResourceManager.GetString("SEGMENT_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_O.
        /// </summary>
        public static string SEGMENT_O {
            get {
                return ResourceManager.GetString("SEGMENT_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGMENT_R.
        /// </summary>
        public static string SEGMENT_R {
            get {
                return ResourceManager.GetString("SEGMENT_R", resourceCulture);
            }
        }
    }
}
