//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSTool.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RebarStructureType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RebarStructureType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSTool.Properties.Langs.RebarStructureType", typeof(RebarStructureType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_腹筋.
        /// </summary>
        public static string BEAM_ABDOMINAL_REBAR {
            get {
                return ResourceManager.GetString("BEAM_ABDOMINAL_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_段取り筋.
        /// </summary>
        public static string BEAM_DANTORI_REBAR {
            get {
                return ResourceManager.GetString("BEAM_DANTORI_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_ふかし筋.
        /// </summary>
        public static string BEAM_FUKASHI_REBAR {
            get {
                return ResourceManager.GetString("BEAM_FUKASHI_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋下端1段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_LOWER_STAGE_1 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_LOWER_STAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋下端2段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_LOWER_STAGE_2 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_LOWER_STAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋下端3段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_LOWER_STAGE_3 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_LOWER_STAGE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋下端4段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_LOWER_STAGE_4 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_LOWER_STAGE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋上端1段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_UPPER_STAGE_1 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_UPPER_STAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋上端2段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_UPPER_STAGE_2 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_UPPER_STAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋上端3段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_UPPER_STAGE_3 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_UPPER_STAGE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_主筋上端4段筋.
        /// </summary>
        public static string BEAM_MAIN_REBAR_UPPER_STAGE_4 {
            get {
                return ResourceManager.GetString("BEAM_MAIN_REBAR_UPPER_STAGE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_その他補強筋.
        /// </summary>
        public static string BEAM_OTHER_REBAR {
            get {
                return ResourceManager.GetString("BEAM_OTHER_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_巾止め.
        /// </summary>
        public static string BEAM_OTHER_REBAR2 {
            get {
                return ResourceManager.GetString("BEAM_OTHER_REBAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_中子.
        /// </summary>
        public static string BEAM_SECONDARY_STP_REBAR {
            get {
                return ResourceManager.GetString("BEAM_SECONDARY_STP_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_STP.
        /// </summary>
        public static string BEAM_STP {
            get {
                return ResourceManager.GetString("BEAM_STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_開口部STP.
        /// </summary>
        public static string BEAM_STP_OPENING {
            get {
                return ResourceManager.GetString("BEAM_STP_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_開口部STP_下.
        /// </summary>
        public static string BEAM_STP_OPENING_BOT {
            get {
                return ResourceManager.GetString("BEAM_STP_OPENING_BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_開口部補強筋.
        /// </summary>
        public static string BEAM_STP_OPENING_OTHER {
            get {
                return ResourceManager.GetString("BEAM_STP_OPENING_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_開口部STP_上.
        /// </summary>
        public static string BEAM_STP_OPENING_TOP {
            get {
                return ResourceManager.GetString("BEAM_STP_OPENING_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_STP_U_DOWN.
        /// </summary>
        public static string BEAM_STP_U_DOWN {
            get {
                return ResourceManager.GetString("BEAM_STP_U_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_STP_U_UP.
        /// </summary>
        public static string BEAM_STP_U_UP {
            get {
                return ResourceManager.GetString("BEAM_STP_U_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁_巾止め.
        /// </summary>
        public static string BEAM_WIDTH_STOPPER {
            get {
                return ResourceManager.GetString("BEAM_WIDTH_STOPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_ふかし筋.
        /// </summary>
        public static string COLUMN_FUKASHI_REBAR {
            get {
                return ResourceManager.GetString("COLUMN_FUKASHI_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_主筋.
        /// </summary>
        public static string COLUMN_MAIN_REBAR {
            get {
                return ResourceManager.GetString("COLUMN_MAIN_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_その他補強筋.
        /// </summary>
        public static string COLUMN_OTHER_REBAR {
            get {
                return ResourceManager.GetString("COLUMN_OTHER_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_巾止め筋.
        /// </summary>
        public static string COLUMN_OTHER_REBAR2 {
            get {
                return ResourceManager.GetString("COLUMN_OTHER_REBAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_芯筋.
        /// </summary>
        public static string COLUMN_OTHER_REBAR3 {
            get {
                return ResourceManager.GetString("COLUMN_OTHER_REBAR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_仕口部帯筋.
        /// </summary>
        public static string COLUMN_REBAR_JOINT_AREA {
            get {
                return ResourceManager.GetString("COLUMN_REBAR_JOINT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_副帯筋.
        /// </summary>
        public static string COLUMN_SECONDARY_STP_REBAR {
            get {
                return ResourceManager.GetString("COLUMN_SECONDARY_STP_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柱_帯筋.
        /// </summary>
        public static string COLUMN_STP_REBAR {
            get {
                return ResourceManager.GetString("COLUMN_STP_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎_段取り筋.
        /// </summary>
        public static string FOUNDATION_DANTORI_REBAR {
            get {
                return ResourceManager.GetString("FOUNDATION_DANTORI_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎_横筋.
        /// </summary>
        public static string FOUNDATION_HORIZONTAL_REBAR {
            get {
                return ResourceManager.GetString("FOUNDATION_HORIZONTAL_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎_ベース筋.
        /// </summary>
        public static string FOUNDATION_MAIN_REBAR {
            get {
                return ResourceManager.GetString("FOUNDATION_MAIN_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎_はかま筋.
        /// </summary>
        public static string FOUNDATION_MAINTOP_REBAR {
            get {
                return ResourceManager.GetString("FOUNDATION_MAINTOP_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎_杭頭補強筋.
        /// </summary>
        public static string FOUNDATION_OTHER_REBAR {
            get {
                return ResourceManager.GetString("FOUNDATION_OTHER_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎_その他補強筋.
        /// </summary>
        public static string FOUNDATION_OTHER_REBAR2 {
            get {
                return ResourceManager.GetString("FOUNDATION_OTHER_REBAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床_下配力筋.
        /// </summary>
        public static string SLAB_BOTTOM_DISTRIBUTION_REBAR {
            get {
                return ResourceManager.GetString("SLAB_BOTTOM_DISTRIBUTION_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床_下主筋.
        /// </summary>
        public static string SLAB_BOTTOM_MAIN_REBAR {
            get {
                return ResourceManager.GetString("SLAB_BOTTOM_MAIN_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床_開口部補強筋.
        /// </summary>
        public static string SLAB_OPENING_REINFORCEMENT_BAR {
            get {
                return ResourceManager.GetString("SLAB_OPENING_REINFORCEMENT_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床_その他補強筋.
        /// </summary>
        public static string SLAB_OTHER_REINFORCEMENT_BARS {
            get {
                return ResourceManager.GetString("SLAB_OTHER_REINFORCEMENT_BARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床_段差部補強筋.
        /// </summary>
        public static string SLAB_STEP_REINFORCEMENT_BAR {
            get {
                return ResourceManager.GetString("SLAB_STEP_REINFORCEMENT_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床_上配力筋.
        /// </summary>
        public static string SLAB_TOP_DISTRIBUTION_REBAR {
            get {
                return ResourceManager.GetString("SLAB_TOP_DISTRIBUTION_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 床_上主筋.
        /// </summary>
        public static string SLAB_TOP_MAIN_REBAR {
            get {
                return ResourceManager.GetString("SLAB_TOP_MAIN_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁_横筋.
        /// </summary>
        public static string WALL_HOIZONTAL_REBAR {
            get {
                return ResourceManager.GetString("WALL_HOIZONTAL_REBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁_開口部補強筋.
        /// </summary>
        public static string WALL_OPENING_REINFORCEMENT_BAR {
            get {
                return ResourceManager.GetString("WALL_OPENING_REINFORCEMENT_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁_その他補強筋.
        /// </summary>
        public static string WALL_OTHER_REINFORCEMENT_BARS {
            get {
                return ResourceManager.GetString("WALL_OTHER_REINFORCEMENT_BARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壁_縦筋.
        /// </summary>
        public static string WALL_VERTICAL_REBAR {
            get {
                return ResourceManager.GetString("WALL_VERTICAL_REBAR", resourceCulture);
            }
        }
    }
}


