//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSTool.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchemaInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchemaInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSTool.Properties.Langs.SchemaInfo", typeof(SchemaInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 672899e6-b944-43f7-99e9-aea7309b0256.
        /// </summary>
        public static string LAP_SCHEMAL_INFO_GUID {
            get {
                return ResourceManager.GetString("LAP_SCHEMAL_INFO_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LapInfo.
        /// </summary>
        public static string LAP_SCHEMAL_INFO_NAME {
            get {
                return ResourceManager.GetString("LAP_SCHEMAL_INFO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e4c2fb9d-9b72-4e7d-8cd6-8d95adf041d0.
        /// </summary>
        public static string REBAR_BEAM_CUT_SCHEMAL_INFO_GUID {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_SCHEMAL_INFO_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebarBeamCutInfo.
        /// </summary>
        public static string REBAR_BEAM_CUT_SCHEMAL_INFO_NAME {
            get {
                return ResourceManager.GetString("REBAR_BEAM_CUT_SCHEMAL_INFO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47037f6d-373d-459b-993c-aef23945fecf.
        /// </summary>
        public static string REBAR_BEAM_SCHEMAL_INFO_GUID {
            get {
                return ResourceManager.GetString("REBAR_BEAM_SCHEMAL_INFO_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebarBeamInfo.
        /// </summary>
        public static string REBAR_BEAM_SCHEMAL_INFO_NAME {
            get {
                return ResourceManager.GetString("REBAR_BEAM_SCHEMAL_INFO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF1770A7-68C3-4686-B234-AE192927C870.
        /// </summary>
        public static string REBAR_SCHEDULE_COMPARE_INFO_GUID {
            get {
                return ResourceManager.GetString("REBAR_SCHEDULE_COMPARE_INFO_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashRebarCompare.
        /// </summary>
        public static string REBAR_SCHEDULE_COMPARE_INFO_NAME {
            get {
                return ResourceManager.GetString("REBAR_SCHEDULE_COMPARE_INFO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2d6582fe-6658-4cdd-92c7-e9aafa233a8e.
        /// </summary>
        public static string REBAR_TYPE_SCHEMA_GUID {
            get {
                return ResourceManager.GetString("REBAR_TYPE_SCHEMA_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebarTypeInfo.
        /// </summary>
        public static string REBAR_TYPE_SCHEMA_NAME {
            get {
                return ResourceManager.GetString("REBAR_TYPE_SCHEMA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63971AB9-78B1-4585-8DF9-9E14E25843A8.
        /// </summary>
        public static string SCHEMAL_REBAR_GEOMETRY_SHAPE_GUID {
            get {
                return ResourceManager.GetString("SCHEMAL_REBAR_GEOMETRY_SHAPE_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebarGeometryShape.
        /// </summary>
        public static string SCHEMAL_REBAR_GEOMETRY_SHAPE_NAME {
            get {
                return ResourceManager.GetString("SCHEMAL_REBAR_GEOMETRY_SHAPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fed30a8b-f35e-4735-a6e9-4eea0ec9c614.
        /// </summary>
        public static string SCHEMAL_REBAR_LAP_GUID {
            get {
                return ResourceManager.GetString("SCHEMAL_REBAR_LAP_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebarLapTypeInfo.
        /// </summary>
        public static string SCHEMAL_REBAR_LAP_NAME {
            get {
                return ResourceManager.GetString("SCHEMAL_REBAR_LAP_NAME", resourceCulture);
            }
        }
    }
}


