//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSTool.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareParameterInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareParameterInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSTool.Properties.Langs.ShareParameterInfo", typeof(ShareParameterInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X方向Lﾌｶｼ.
        /// </summary>
        public static string COLUMN_FUKASHI_X_L {
            get {
                return ResourceManager.GetString("COLUMN_FUKASHI_X_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X方向Rﾌｶｼ.
        /// </summary>
        public static string COLUMN_FUKASHI_X_R {
            get {
                return ResourceManager.GetString("COLUMN_FUKASHI_X_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y方向Lﾌｶｼ.
        /// </summary>
        public static string COLUMN_FUKASHI_Y_L {
            get {
                return ResourceManager.GetString("COLUMN_FUKASHI_Y_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y方向Rﾌｶｼ.
        /// </summary>
        public static string COLUMN_FUKASHI_Y_R {
            get {
                return ResourceManager.GetString("COLUMN_FUKASHI_Y_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁下端増打.
        /// </summary>
        public static string FUKASHI_BOTTOM {
            get {
                return ResourceManager.GetString("FUKASHI_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふかし厚さ_下.
        /// </summary>
        public static string FUKASHI_BOTTOM_1 {
            get {
                return ResourceManager.GetString("FUKASHI_BOTTOM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁側面増打1.
        /// </summary>
        public static string FUKASHI_LEFT {
            get {
                return ResourceManager.GetString("FUKASHI_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふかし厚さ_左.
        /// </summary>
        public static string FUKASHI_LEFT_1 {
            get {
                return ResourceManager.GetString("FUKASHI_LEFT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁側面増打2.
        /// </summary>
        public static string FUKASHI_RIGHT {
            get {
                return ResourceManager.GetString("FUKASHI_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふかし厚さ_右.
        /// </summary>
        public static string FUKASHI_RIGHT_1 {
            get {
                return ResourceManager.GetString("FUKASHI_RIGHT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梁上端増打.
        /// </summary>
        public static string FUKASHI_TOP {
            get {
                return ResourceManager.GetString("FUKASHI_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ふかし厚さ_上.
        /// </summary>
        public static string FUKASHI_TOP_1 {
            get {
                return ResourceManager.GetString("FUKASHI_TOP_1", resourceCulture);
            }
        }
    }
}


